### ISSUE TITLE
State and jti attributes should not be in BoxApplication

### ISSUE THREAD

**Issue by MatthijsDB** [Nokavision/BoxConnector#3]
The attributes **state** and **jti** should not be in the BoxApplication entity. The values for these attributes should be automatically generated when requesting a token from Box. 

Especially the state attribute. When requesting a token for a normal user with OAuth, the Box platform will respond with a request containing the same state value. Therefore, our application needs to wait for this response and compare the state value returned by Box with the one that was given.

Also, the value for jti should be created when requesting a token. The documentation says: "A unique identifier specified by the client for this JWT". If Box sticks to the rules of JWT, the platform should check if the given jti has not been used before. Therefore, we have to make sure to create some unique random string for each request.

_P.S.  I created this issue in the Nokavision repo, because the mendix repo doesn't let me create an issue._

**Comment by MxAdmin** [comment]
May I suggest the following persisten entities in the domain model?

![image](https://cloud.githubusercontent.com/assets/20298978/23787061/7e2dc0ee-0570-11e7-8137-f553f80b470d.png)

This can also be found in the branch I created: TokenRequestAdditions

**Comment by RaphaelAudet** [comment]
I agree, the jti at least should be random and moving them out of the Application makes sense.

As for Box refusing to honor a request with a previously used jti, it doesn't seem to be the case, but this shouldn't stop use from using random values.

_@MxAdmin:  the mendix/BoxConnector repo currently serves as a fork for deploying to the mendix appstore, all changes will be proposed in the Nokavision/BoxConnector repo._

**Comment by clairemalcor** [comment]
This issue will be solved later when the Service Account will be fully implemented.
