### ISSUE TITLE
GetTokenServiceAccountImpl uses wrong Exp

### ISSUE THREAD

**Issue by MatthijsDB** [Nokavision/BoxConnector#4]
The GetTokenServiceAccountImpl microflow creates a wrong JWT request because the value of the claims attribute **exp** is not set correctly. This should be set to a Unix timestamp, but the microflow is using the "GetIntFromDateTime" Java action with 'day' as selector which gives a number from 1 to 31.

We need to get the number of seconds since 1-1-1970 (UTC) and add a maximum of 60 seconds to create a valid JWT claims.

**Comment by clairemalcor** [comment]
This issue will be solved later when the Service Account will be fully implemented.
